openapi: 3.0.0
info:
  title: department
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /departments/:
    get:
      summary: Get all departments
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: array
                items:
                  $ref: '#/components/schemas/department'
              examples:
                예시:
                  value:
                    - id: 1
                      name: 컴퓨터공학부
                      college: 공과대학
                      link: 'https://cse.snu.ac.kr/'
                      tags:
                        - 입학
                        - 졸업
                        - 수업
                      follow:
                        - 졸업
                    - id: 2
                      name: 기계공학부
                      college: 공과대학
                      link: 'https://me.snu.ac.kr/'
                      tags:
                        - 학부
                        - 대학원
                      follow:
                        - 대학원
        '401':
          description: |-
            Unauthorized
            토큰 재발급 혹은 로그인 필요
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      operationId: get-departments
      description: |-
        모든 과의 정보 리턴

        가능한 단과대학의 종류는 다음과 같다.
        ```
        export const ENGINEERING = '공과대학';
        export const HUMANITIES = '인문대학';
        export const SOCIAL = '사회과학대학';
        export const SCIENCE = '자연과학대학';
        export const NURSING = '간호대학';
        export const CBA = '경영대학';
        export const CALS = '농업생명과학대학';
        export const ART = '미술대학';
        export const EDU = '사범대학';
        export const CHE = '생활과학대학';
        export const VET = '수의과대학';
        export const PHARM = '약학대학';
        export const MUSIC = '음악대학';
        export const MEDICINE = '의과대학';
        export const CLS = '자유전공학부';
        export const ETC = '기타';
        ```
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
    parameters: []
  '/departments/{department_id}':
    get:
      summary: Get department by department id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/department'
              examples:
                example-1:
                  value:
                    id: 1
                    name: 컴퓨터공학부
                    college: 공과대학
                    link: 'https://cse.snu.ac.kr/'
                    tags:
                      - 입학
                      - 졸업
                      - 수업
                    follow:
                      - 졸업
        '401':
          description: |-
            Unauthorized
            토큰 재발급 혹은 로그인 필요
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      operationId: get-department-follow
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
      description: id에 해당하는 과의 정보 리턴
    parameters:
      - schema:
          type: string
        name: department_id
        in: path
        required: true
        description: 과 id
  '/departments/{department_id}/follow':
    parameters:
      - schema:
          type: string
        name: department_id
        in: path
        required: true
    post:
      summary: create department follow
      operationId: post-departments-department_id-follow
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/department'
              examples:
                example-1:
                  value:
                    id: 1
                    name: 컴퓨터공학부
                    college: 공과대학
                    link: 'https://cse.snu.ac.kr/'
                    tags:
                      - 입학
                      - 졸업
                      - 수업
                    follow:
                      - 졸업
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                example-1:
                  value:
                    statusCode: 400
                    message: already followed tag
                    error: Bad Request
                example-2:
                  value:
                    statusCode: 400
                    message: 'There is no tag with the given name: 장학rm'
                    error: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      description: 'create department follow, 이미 생성되어있다면 400, '
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                follow:
                  type: string
              required:
                - follow
            examples:
              example-1:
                value:
                  follow: 장학
    delete:
      summary: Delete department follow
      operationId: delete-departments-department_id-follow
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/department'
              examples:
                example-1:
                  value:
                    id: 1
                    name: 컴퓨터공학부
                    college: 공과대학
                    link: 'https://cse.snu.ac.kr/'
                    tags:
                      - 입학
                      - 졸업
                      - 수업
                    follow:
                      - 졸업
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                example-1:
                  value:
                    statusCode: 400
                    message: 'There is no tag with the given name: 장학rm'
                    error: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      description: 'Delete department follow, 이미 지운 것을 다시 지우는 경우 204.204를 리턴하는 경우 department informantion은 제공하지 않는다.'
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                follow:
                  type: string
            examples:
              example-1:
                value:
                  follow: 장학
components:
  schemas:
    department:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 65
          name: 컴퓨터공학부
          college: 공과대학
          link: ''
          tags:
            - 학사 (학부)
            - 연합전공 인공지능
            - 학생공지 (교내)
            - 졸업
            - 제2전공/전과
            - 수업
            - 학사 (대학원)
            - 입학
            - 교환학생/유학
            - 등록/복학/휴학/재입학
            - 장학
            - 인턴/취업 (공식 게시)
            - 기업게시판
            - 미분류
            - 외부 행사/프로그램
            - 세미나
            - 자료실
          follow: []
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        college:
          type: string
          minLength: 1
        link:
          type: string
        tags:
          type: array
          items: {}
        follow:
          type: array
          items: {}
      required:
        - id
        - name
        - college
        - link
        - tags
        - follow
