openapi: 3.0.0
info:
  title: notice
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/notices/{notice_id}':
    parameters:
      - schema:
          type: string
        name: notice_id
        in: path
        required: true
        description: 공지사항의 id
    get:
      summary: Get Notice by Notice ID
      tags: []
      responses:
        '200':
          description: |-
            OK

            - `preview`: content를 text화 이후 `\n` -> ` ` 이후 200자 제한
            - `content`: `\n` -> `&#10;`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notice'
              examples:
                example-1:
                  value:
                    id: 27695
                    title: 캠퍼스 라이선스 소프트웨어 및 폰트파일 사용시 주의사항 안내
                    content: "<p>서울대학교 캠퍼스 라이선스 소프트웨어 이용 활성화와<strong> 불법 소프트웨어 사용 근절</strong>을 안내 드립니다.</p>\n\n<p>또한 최근 <strong>폰트파일 저작권</strong> 침해 이슈에 따라 폰트파일 사용시 주의사항을 안내드리오니,\_<br>\n<br>\n소프트웨어 및 폰트파일 사용에 유의하시기 바랍니다.<br>\n\_</p>\n\n<p align=\"left\" class=\"MsoNoSpacing\" style=\"margin: 0cm 0cm 0pt; text-align: left;\"><span style=\"font-family: 돋움, dotum;\"><span style=\"font-family: 돋움, dotum;\"><span style=\"color: rgb(255, 0, 0); font-family: 돋움, dotum; font-size: 10pt;\"><span style=\"color: rgb(255, 0, 0); font-size: 10pt;\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><font color=\"#61b977\"><span style=\"font-size: 12pt;\"><span style=\"line-height: 107%; font-family: 굴림; font-size: 9pt;\"><span><span lang=\"EN-US\"><strong><font color=\"#320251\" face=\"Gulim\"><a href=\"http://board.snu.ac.kr/apiboard/140/10000000155075?boardId=140\" target=\"_blank\">※ 서울대학교 캠퍼스 라이선스 소프트웨어 이용안내 및 불법 소프트웨어 사용 금지 공지 보기 (클릭)</a></font></strong></span></span></span></span></font></span></span></span></span></span></span></span></span></span></span><br>\n<br>\n붙임 1. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%841%292015%EB%85%84%20%EC%BA%A0%ED%8D%BC%EC%8A%A4%20%EB%9D%BC%EC%9D%B4%EC%84%A0%EC%8A%A4%20%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4%20%EC%9D%B4%EC%9A%A9%EC%95%88%EB%82%B4.hwp\" target=\"_blank\">2015년 캠퍼스 라이선스 소프트웨어 이용안내 1부</a><br>\n\_\_\_\_\_\_ 2. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%842%29%EB%B6%88%EB%B2%95%20%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4%20%EC%82%AC%EC%9A%A9%20%EA%B8%88%EC%A7%80%20%EC%95%88%EB%82%B4.hwp\" target=\"_blank\">불법 소프트웨어 사용 금지 안내 1부</a><br>\n\_\_ \_\_\_ 3. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%843%29%ED%8F%B0%ED%8A%B8%ED%8C%8C%EC%9D%BC%20%EC%82%AC%EC%9A%A9%EC%8B%9C%20%EC%A3%BC%EC%9D%98%EC%82%AC%ED%95%AD%20%EC%95%88%EB%82%B4.hwp\" target=\"_blank\">폰트파일 사용시 주의사항 안내 1부</a><br>\n\_\_\_\_\_ \_4. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%844%29%EB%AC%B8%ED%99%94%EC%B2%B4%EC%9C%A1%EA%B4%80%EA%B4%91%EB%B6%80%20%ED%8F%B0%ED%8A%B8%ED%8C%8C%EC%9D%BC%20%EC%A0%80%EC%9E%91%EA%B6%8C%20%EC%95%88%EB%82%B4.pdf\" target=\"_blank\">문화체육관광부 폰트파일 저작권 안내 1부</a><br>\n\_\_ \_\_\_ 5. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%845%29%ED%95%9C%EC%BB%B4%EC%98%A4%ED%94%BC%EC%8A%A4%20%EB%B2%88%EB%93%A4%EC%84%9C%EC%B2%B4%20%EB%9D%BC%EC%9D%B4%EC%84%A0%EC%8A%A4%20%EC%95%88%EB%82%B4%EC%9D%98%20%EA%B1%B4.pdf\" target=\"_blank\">한컴오피스 번들서체 라이선스 안내의 건 1부</a><br>\n\_\_ \_\_\_\_6. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%EC%84%9C%EC%9A%B8%EB%8C%80%ED%95%99%EA%B5%90%20%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4%20%EA%B4%80%EB%A6%AC%20%EC%A7%80%EC%B9%A8.pdf\" target=\"_blank\">서울대학교 소프트웨어 관리 지침 1부</a>.\_ 끝.</p>\n\t\t"
                    created_at: '2017-12-05T08:39:58.000Z'
                    is_pinned: true
                    link: 'https://me.snu.ac.kr/ko/board/freeboard/view/10984'
                    files: []
                    is_scrapped: false
                    department_id: 71
                    department_name: 기계공학부
                    tags:
                      - 자유게시판
                    style: 'ol { list-style-type : none;}'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
        '404':
          description: Notice Not Found
      operationId: get-notices-id
      description: Id에 따른 공지사항을 리턴
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
  '/notices/department/{department_id}':
    parameters:
      - schema:
          type: string
        name: department_id
        in: path
        required: true
    get:
      summary: Get Notices by Department ID
      operationId: get-notices-department
      responses:
        '200':
          description: |-
            OK

            - `next_cursor` : 마지막 페이지인 경우 "" 반환 (Empty String)
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  notices:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      $ref: '#/components/schemas/NoticeSummary'
                  next_cursor:
                    type: string
                    minLength: 1
                required:
                  - notices
                  - next_cursor
              examples:
                example-1:
                  value:
                    notices:
                      - id: 27923
                        title: 2021학년도 일주학술문화재단 해외박사 장학생 선발 안내
                        created_at: '2021-04-01T06:48:00.000Z'
                        is_pinned: false
                        link: 'https://cse.snu.ac.kr/node/49005'
                        is_scrapped: false
                        preview: "안녕하세요,\n\n동 재단에서 2021학년도 해외박사 장학생을 아래와 같이 선발함을 알려드립니다.\n\_\n\n가. 지원기간: 2021.4.6(화) 9:00 ~ 4.23(금) 18:00\n\n나. 지원방법: 홈페이지 (www.iljufoundation.org) 온라인 접수\n\n다. 지원자격 ※ 아래 3가지 요건 모두 충족 시\n\n1) 해외 우수 대학원 박사과정(PhD)의 입학허가 받은 신입생(재학생 지원 불가)\n\n2) 대한민국 국적 보유자 (국외 영주권자 또는 "
                        department_id: 65
                        department_name: 컴퓨터공학부
                        tags:
                          - 학사 (대학원)
                          - 장학
                    next_cursor: 1617080460000-28105
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                example-1:
                  value:
                    statusCode: 400
                    message: limit must be a positive number
                    error: Bad Request
                example-2:
                  value:
                    statusCode: 400
                    message: invalid cursor format
                    error: Bad Request
                example-3:
                  value:
                    statusCode: 400
                    message: There is no department with the id 3
                    error: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      description: |
        해당 과의 (모든/pin 되어있는/태그별) 공지사항 리턴
      parameters:
        - schema:
            type: boolean
          in: query
          name: pinned
          description: true인 경우 pin되어 있는 공지사항만 리턴
        - schema:
            type: string
          in: query
          name: tags
          description: '특정 태그에 해당하는 공지사항만 리턴, 여러개의 태그는 쉼표'',''로 구분, default = ''all'''
        - schema:
            type: string
          in: query
          name: cursor
          description: pagination/ cursor (없을 시 첫 번째 페이지)
        - schema:
            type: integer
          in: query
          name: limit
          description: pagination/ 가져오는 notice 수
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
  /notices/follow:
    get:
      summary: Get Notices by Following Info
      tags: []
      responses:
        '200':
          description: |-
            OK

            - `next_cursor` : 마지막 페이지인 경우 "" 반환 (Empty String)
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  notices:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      $ref: '#/components/schemas/NoticeSummary'
                  next_cursor:
                    type: string
                    minLength: 1
                required:
                  - notices
                  - next_cursor
              examples:
                example-1:
                  value:
                    notices:
                      - id: 27923
                        title: 2021학년도 일주학술문화재단 해외박사 장학생 선발 안내
                        created_at: '2021-04-01T06:48:00.000Z'
                        is_pinned: false
                        link: 'https://cse.snu.ac.kr/node/49005'
                        is_scrapped: false
                        preview: "안녕하세요,\n\n동 재단에서 2021학년도 해외박사 장학생을 아래와 같이 선발함을 알려드립니다.\n\_\n\n가. 지원기간: 2021.4.6(화) 9:00 ~ 4.23(금) 18:00\n\n나. 지원방법: 홈페이지 (www.iljufoundation.org) 온라인 접수\n\n다. 지원자격 ※ 아래 3가지 요건 모두 충족 시\n\n1) 해외 우수 대학원 박사과정(PhD)의 입학허가 받은 신입생(재학생 지원 불가)\n\n2) 대한민국 국적 보유자 (국외 영주권자 또는 "
                        department_id: 65
                        department_name: 컴퓨터공학부
                        tags:
                          - 학사 (대학원)
                          - 장학
                    next_cursor: 1617080460000-28105
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                example-1:
                  value:
                    statusCode: 400
                    message: limit must be a positive number
                    error: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      operationId: get-notices
      description: |
        팔로우하는 과의 공지사항을 리턴
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
        - schema:
            type: string
          in: query
          name: cursor
          description: pagination/ cursor (없을 시 첫 번째 페이지)
        - schema:
            type: integer
          in: query
          name: limit
          required: true
          description: pagination/ 가져오는 notice 수
    parameters: []
  /notices/follow/search:
    get:
      summary: Search Notices w/ following tags
      tags: []
      responses:
        '200':
          description: |-
            OK

            - `next_cursor` : 마지막 페이지인 경우 "" 반환 (Empty String)
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  notices:
                    type: array
                    uniqueItems: true
                    items:
                      $ref: '#/components/schemas/NoticeSummary'
                  next_cursor:
                    type: string
                    minLength: 1
                required:
                  - next_cursor
              examples:
                example-1:
                  value:
                    notices:
                      - id: 27923
                        title: 2021학년도 일주학술문화재단 해외박사 장학생 선발 안내
                        created_at: '2021-04-01T06:48:00.000Z'
                        is_pinned: false
                        link: 'https://cse.snu.ac.kr/node/49005'
                        is_scrapped: false
                        preview: "안녕하세요,\n\n동 재단에서 2021학년도 해외박사 장학생을 아래와 같이 선발함을 알려드립니다.\n\_\n\n가. 지원기간: 2021.4.6(화) 9:00 ~ 4.23(금) 18:00\n\n나. 지원방법: 홈페이지 (www.iljufoundation.org) 온라인 접수\n\n다. 지원자격 ※ 아래 3가지 요건 모두 충족 시\n\n1) 해외 우수 대학원 박사과정(PhD)의 입학허가 받은 신입생(재학생 지원 불가)\n\n2) 대한민국 국적 보유자 (국외 영주권자 또는 "
                        department_id: 65
                        department_name: 컴퓨터공학부
                        tags:
                          - 학사 (대학원)
                          - 장학
                    next_cursor: 1617080460000-28105
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                example-1:
                  value:
                    statusCode: 400
                    message: limit must be a positive number
                    error: Bad Request
                example-2:
                  value:
                    statusCode: 400
                    message: keywords must be a string
                    error: Bad Request
                example-3:
                  value:
                    statusCode: 400
                    message: '''keywords'' should not be empty'
                    error: Bad Request
                example-4:
                  value:
                    statusCode: 400
                    message: At least one of 'title' and 'content' should be true
                    error: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      operationId: get-notices-follow-search
      parameters:
        - schema:
            type: string
          in: query
          name: keywords
          description: 검색할 키워드
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
        - schema:
            type: string
          in: query
          name: cursor
          description: pagination/ cursor (없을 시 첫 번째 페이지)
        - schema:
            type: integer
          in: query
          name: limit
          required: true
          description: pagination/ 가져오는 notice 수
      description: |
        유저가 팔로우하는 태그에 해당하는 공지사항 중에 제목 또는 내용에 키워드를 포함한 공지사항들을 검색한다. 공백이 포함된 문자열을 받는 경우 공백을 기준으로 split한 단어들에 대해 AND 연산으로 검색을 진행한다.

        title과 content가 모두 true이면 제목 및 내용 검색으로 동작(두개의 결과를 OR)
        title과 content 둘 중 하나는 true여야한다.
    parameters: []
  /notices/scrap:
    get:
      summary: Get Scrapped Notices
      tags: []
      responses:
        '200':
          description: |-
            OK

            - `next_cursor` : 마지막 페이지인 경우 "" 반환 (Empty String)
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  notices:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      $ref: '#/components/schemas/NoticeSummary'
                  next_cursor:
                    type: string
                    minLength: 1
                required:
                  - notices
                  - next_cursor
              examples:
                example-1:
                  value:
                    notices:
                      - id: 27923
                        title: 2021학년도 일주학술문화재단 해외박사 장학생 선발 안내
                        created_at: '2021-04-01T06:48:00.000Z'
                        is_pinned: false
                        link: 'https://cse.snu.ac.kr/node/49005'
                        is_scrapped: false
                        preview: "안녕하세요,\n\n동 재단에서 2021학년도 해외박사 장학생을 아래와 같이 선발함을 알려드립니다.\n\_\n\n가. 지원기간: 2021.4.6(화) 9:00 ~ 4.23(금) 18:00\n\n나. 지원방법: 홈페이지 (www.iljufoundation.org) 온라인 접수\n\n다. 지원자격 ※ 아래 3가지 요건 모두 충족 시\n\n1) 해외 우수 대학원 박사과정(PhD)의 입학허가 받은 신입생(재학생 지원 불가)\n\n2) 대한민국 국적 보유자 (국외 영주권자 또는 "
                        department_id: 65
                        department_name: 컴퓨터공학부
                        tags:
                          - 학사 (대학원)
                          - 장학
                    next_cursor: 1617080460000-28105
        '400':
          description: 'Bad Request, invlaid offset or limit'
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                example-1:
                  value:
                    statusCode: 400
                    message: limit must be a positive number
                    error: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      operationId: get-notices-scrap
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
        - schema:
            type: string
          in: query
          name: cursor
          description: pagination/ cursor (없을 시 첫 번째 페이지)
        - schema:
            type: integer
          in: query
          name: limit
          description: pagination/ 가져오는 notice 수
          required: true
      description: |
        유저가 스크랩한 공지사항을 리턴
  '/notices/{notice_id}/scrap':
    parameters:
      - schema:
          type: integer
        name: notice_id
        in: path
        required: true
    post:
      summary: Post notice scrap
      operationId: post-notices-notice_id-scrap
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notice'
              examples:
                example-1:
                  value:
                    id: 1
                    department_name: 컴퓨터공학부
                    department_id: 5
                    title: '2021학년도 1학기 컴퓨터공학부 개설 교과목 ''정원 외 신청(구: 초안지)'' 안내'
                    preview: 2021학년도 1학기부터 서울대학교 운영방법 변경에 따라 ...
                    content: '<p>&#xD559;&#xC0DD; &#xC5EC;&#xB7EC;&#xBD84;&#xAED8;,</p>'
                    created_at: '2021-02-02T15:38:22Z'
                    tags:
                      - 수업
                      - 학사 (학부)
                      - 학사 (대학원)
                      - 제2전공/전과
                    is_pinned: true
                    link: 'https://cse.snu.ac.kr/node/47377'
                    files:
                      - id: 0
                        name: (국문) 2021년 1학기 정원외신청 매뉴얼_학생.pdf
                        link: 'https://cse.snu.ac.kr/sites/default/files/node--notice/%28%EA%B5%AD%EB%AC%B8%29%202021%EB%85%84%201%ED%95%99%EA%B8%B0%20%EC%A0%95%EC%9B%90%EC%99%B8%EC%8B%A0%EC%B2%AD%20%EB%A7%A4%EB%89%B4%EC%96%BC_%ED%95%99%EC%83%9D.pdf'
                    is_scrapped: true
                    style: 'ol { list-style-type : none;}'
        '400':
          description: Already scrapped
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
        '404':
          description: Not Found
      description: '게시글 스크랩 하기. 이미 스크랩한 경우 400, 게시글이 존재하지 않으면 404를 리턴합니다.'
    delete:
      summary: Delete notice scrap
      operationId: delete-notices-notice_id-scrap
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notice'
              examples:
                example-1:
                  value:
                    id: 1
                    department_name: 컴퓨터공학부
                    department_id: 5
                    title: '2021학년도 1학기 컴퓨터공학부 개설 교과목 ''정원 외 신청(구: 초안지)'' 안내'
                    preview: 2021학년도 1학기부터 서울대학교 운영방법 변경에 따라 ...
                    content: '<p>&#xD559;&#xC0DD; &#xC5EC;&#xB7EC;&#xBD84;&#xAED8;,</p>'
                    created_at: '2021-02-02T15:38:22Z'
                    tags:
                      - 수업
                      - 학사 (학부)
                      - 학사 (대학원)
                      - 제2전공/전과
                    is_pinned: true
                    link: 'https://cse.snu.ac.kr/node/47377'
                    files:
                      - id: 0
                        name: (국문) 2021년 1학기 정원외신청 매뉴얼_학생.pdf
                        link: 'https://cse.snu.ac.kr/sites/default/files/node--notice/%28%EA%B5%AD%EB%AC%B8%29%202021%EB%85%84%201%ED%95%99%EA%B8%B0%20%EC%A0%95%EC%9B%90%EC%99%B8%EC%8B%A0%EC%B2%AD%20%EB%A7%A4%EB%89%B4%EC%96%BC_%ED%95%99%EC%83%9D.pdf'
                    is_scrapped: false
                    style: 'ol { list-style-type : none;}'
        '204':
          description: No Content. already deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./user.v1.yaml#/components/schemas/Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
        '404':
          description: Not Found
      description: '게시글 스크랩을 취소합니다. 스크랩이 되어있지 않은 경우 204, 게시글이 없으면 404를 리턴합니다'
  '/notices/department/{department_id}/search':
    parameters:
      - schema:
          type: string
        name: department_id
        in: path
        required: true
    get:
      summary: Search notices w/ department_id
      tags: []
      responses:
        '200':
          description: |-
            OK

            - `next_cursor` : 마지막 페이지인 경우 "" 반환 (Empty String)
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  notices:
                    type: array
                    uniqueItems: true
                    items:
                      $ref: '#/components/schemas/NoticeSummary'
                  next_cursor:
                    type: string
                    minLength: 1
                required:
                  - notices
                  - next_cursor
              examples:
                example-1:
                  value:
                    notices:
                      - id: 27923
                        title: 2021학년도 일주학술문화재단 해외박사 장학생 선발 안내
                        created_at: '2021-04-01T06:48:00.000Z'
                        is_pinned: false
                        link: 'https://cse.snu.ac.kr/node/49005'
                        is_scrapped: false
                        preview: "안녕하세요,\n\n동 재단에서 2021학년도 해외박사 장학생을 아래와 같이 선발함을 알려드립니다.\n\_\n\n가. 지원기간: 2021.4.6(화) 9:00 ~ 4.23(금) 18:00\n\n나. 지원방법: 홈페이지 (www.iljufoundation.org) 온라인 접수\n\n다. 지원자격 ※ 아래 3가지 요건 모두 충족 시\n\n1) 해외 우수 대학원 박사과정(PhD)의 입학허가 받은 신입생(재학생 지원 불가)\n\n2) 대한민국 국적 보유자 (국외 영주권자 또는 "
                        department_id: 65
                        department_name: 컴퓨터공학부
                        tags:
                          - 학사 (대학원)
                          - 장학
                    next_cursor: 1617080460000-28105
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                example-1:
                  value:
                    statusCode: 400
                    message: limit must be a positive number
                    error: Bad Request
                example-2:
                  value:
                    statusCode: 400
                    message: keywords must be a string
                    error: Bad Request
                example-3:
                  value:
                    statusCode: 400
                    message: '''keywords'' should not be empty'
                    error: Bad Request
                example-4:
                  value:
                    statusCode: 400
                    message: keyword should have at least 2 characters
                    error: Bad Request
        '401':
          description: Unauthorized
      operationId: get-notices-department-department_id-search
      description: |-
        해당 학과 공지사항 중에 제목 또는 내용에 키워드를 포함한 공지사항들을 검색한다. 공백이 포함된 문자열을 받는 경우 공백을 기준으로 split한 단어들에 대해 AND 연산으로 검색을 진행한다.

        검색하는 키워드는 모두 2글자 이상이어야 한다.

        tags의 경우 주어진 경우 해당 학과의 주어진 태그에 해당하는 공지사항들만 검색 (주어지지 않은 경우 해당 학과의 모든 태그)

        pinned의 경우 true로 주어진 경우 해당 학과의 고정된 공지사항들 중에서 검색 (주어지지 않은 경우 해당 학과의 모든 공지사항 중에서 검색)

        tags와 pinned는 함께 적용 가능
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
        - schema:
            type: string
          in: query
          name: keywords
          description: 키워드
          required: true
        - schema:
            type: string
          in: query
          name: cursor
          description: pagination/ cursor (없을 시 첫 번째 페이지)
        - schema:
            type: string
          in: query
          name: limit
          description: pagination/ 가져오는 notice 수
          required: true
        - schema:
            type: string
          in: query
          name: pinned
          description: true인 경우 pin되어 있는 공지사항만 리턴
        - schema:
            type: string
          in: query
          name: tags
          description: '특정 태그에 해당하는 공지사항만 리턴, 여러개의 태그는 쉼표'',''로 구분, default = ''all'''
components:
  schemas:
    Notice:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 27695
          title: 캠퍼스 라이선스 소프트웨어 및 폰트파일 사용시 주의사항 안내
          content: "<p>서울대학교 캠퍼스 라이선스 소프트웨어 이용 활성화와<strong> 불법 소프트웨어 사용 근절</strong>을 안내 드립니다.</p>\n\n<p>또한 최근 <strong>폰트파일 저작권</strong> 침해 이슈에 따라 폰트파일 사용시 주의사항을 안내드리오니,\_<br>\n<br>\n소프트웨어 및 폰트파일 사용에 유의하시기 바랍니다.<br>\n\_</p>\n\n<p align=\"left\" class=\"MsoNoSpacing\" style=\"margin: 0cm 0cm 0pt; text-align: left;\"><span style=\"font-family: 돋움, dotum;\"><span style=\"font-family: 돋움, dotum;\"><span style=\"color: rgb(255, 0, 0); font-family: 돋움, dotum; font-size: 10pt;\"><span style=\"color: rgb(255, 0, 0); font-size: 10pt;\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><span style=\"color: rgb(0, 158, 37);\"><font color=\"#61b977\"><span style=\"font-size: 12pt;\"><span style=\"line-height: 107%; font-family: 굴림; font-size: 9pt;\"><span><span lang=\"EN-US\"><strong><font color=\"#320251\" face=\"Gulim\"><a href=\"http://board.snu.ac.kr/apiboard/140/10000000155075?boardId=140\" target=\"_blank\">※ 서울대학교 캠퍼스 라이선스 소프트웨어 이용안내 및 불법 소프트웨어 사용 금지 공지 보기 (클릭)</a></font></strong></span></span></span></span></font></span></span></span></span></span></span></span></span></span></span><br>\n<br>\n붙임 1. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%841%292015%EB%85%84%20%EC%BA%A0%ED%8D%BC%EC%8A%A4%20%EB%9D%BC%EC%9D%B4%EC%84%A0%EC%8A%A4%20%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4%20%EC%9D%B4%EC%9A%A9%EC%95%88%EB%82%B4.hwp\" target=\"_blank\">2015년 캠퍼스 라이선스 소프트웨어 이용안내 1부</a><br>\n\_\_\_\_\_\_ 2. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%842%29%EB%B6%88%EB%B2%95%20%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4%20%EC%82%AC%EC%9A%A9%20%EA%B8%88%EC%A7%80%20%EC%95%88%EB%82%B4.hwp\" target=\"_blank\">불법 소프트웨어 사용 금지 안내 1부</a><br>\n\_\_ \_\_\_ 3. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%843%29%ED%8F%B0%ED%8A%B8%ED%8C%8C%EC%9D%BC%20%EC%82%AC%EC%9A%A9%EC%8B%9C%20%EC%A3%BC%EC%9D%98%EC%82%AC%ED%95%AD%20%EC%95%88%EB%82%B4.hwp\" target=\"_blank\">폰트파일 사용시 주의사항 안내 1부</a><br>\n\_\_\_\_\_ \_4. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%844%29%EB%AC%B8%ED%99%94%EC%B2%B4%EC%9C%A1%EA%B4%80%EA%B4%91%EB%B6%80%20%ED%8F%B0%ED%8A%B8%ED%8C%8C%EC%9D%BC%20%EC%A0%80%EC%9E%91%EA%B6%8C%20%EC%95%88%EB%82%B4.pdf\" target=\"_blank\">문화체육관광부 폰트파일 저작권 안내 1부</a><br>\n\_\_ \_\_\_ 5. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%28%EB%B6%99%EC%9E%845%29%ED%95%9C%EC%BB%B4%EC%98%A4%ED%94%BC%EC%8A%A4%20%EB%B2%88%EB%93%A4%EC%84%9C%EC%B2%B4%20%EB%9D%BC%EC%9D%B4%EC%84%A0%EC%8A%A4%20%EC%95%88%EB%82%B4%EC%9D%98%20%EA%B1%B4.pdf\" target=\"_blank\">한컴오피스 번들서체 라이선스 안내의 건 1부</a><br>\n\_\_ \_\_\_\_6. <a href=\"/sites/me.snu.ac.kr/files/board/notice/%EC%84%9C%EC%9A%B8%EB%8C%80%ED%95%99%EA%B5%90%20%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4%20%EA%B4%80%EB%A6%AC%20%EC%A7%80%EC%B9%A8.pdf\" target=\"_blank\">서울대학교 소프트웨어 관리 지침 1부</a>.\_ 끝.</p>\n\t\t"
          created_at: '2017-12-05T08:39:58.000Z'
          is_pinned: true
          link: 'https://me.snu.ac.kr/ko/board/freeboard/view/10984'
          files: []
          is_scrapped: false
          department_id: 71
          department_name: 기계공학부
          tags:
            - 자유게시판
      properties:
        id:
          type: number
        title:
          type: string
          minLength: 1
        content:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        is_pinned:
          type: boolean
        link:
          type: string
          minLength: 1
        files:
          type: array
          items:
            type: object
        is_scrapped:
          type: boolean
        department_id:
          type: number
        department_name:
          type: string
          minLength: 1
        tags:
          type: array
          items:
            type: object
        style:
          type: string
      required:
        - id
        - title
        - content
        - created_at
        - is_pinned
        - link
        - files
        - is_scrapped
        - department_id
        - department_name
        - tags
    File:
      title: File
      type: object
      description: 첨부파일
      x-examples:
        example-1:
          id: 0
          name: (국문) 2021년 1학기 정원외신청 매뉴얼_학생.pdf
          link: 'https://cse.snu.ac.kr/sites/default/files/node--notice/%28%EA%B5%AD%EB%AC%B8%29%202021%EB%85%84%201%ED%95%99%EA%B8%B0%20%EC%A0%95%EC%9B%90%EC%99%B8%EC%8B%A0%EC%B2%AD%20%EB%A7%A4%EB%89%B4%EC%96%BC_%ED%95%99%EC%83%9D.pdf'
      properties:
        id:
          type: number
        name:
          type: string
        link:
          type: string
    NoticeSummary:
      description: ''
      type: object
      properties:
        id:
          type: number
        title:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        is_pinned:
          type: boolean
        link:
          type: string
          minLength: 1
        is_scrapped:
          type: boolean
        preview:
          type: string
          minLength: 1
        department_id:
          type: number
        department_name:
          type: string
          minLength: 1
        tags:
          type: array
          items:
            required: []
            properties: {}
      required:
        - id
        - title
        - created_at
        - is_pinned
        - link
        - is_scrapped
        - preview
        - department_id
        - department_name
        - tags
      x-examples:
        example-1:
          id: 27923
          title: 2021학년도 일주학술문화재단 해외박사 장학생 선발 안내
          created_at: '2021-04-01T06:48:00.000Z'
          is_pinned: false
          link: 'https://cse.snu.ac.kr/node/49005'
          is_scrapped: false
          preview: "안녕하세요,\n\n동 재단에서 2021학년도 해외박사 장학생을 아래와 같이 선발함을 알려드립니다.\n\_\n\n가. 지원기간: 2021.4.6(화) 9:00 ~ 4.23(금) 18:00\n\n나. 지원방법: 홈페이지 (www.iljufoundation.org) 온라인 접수\n\n다. 지원자격 ※ 아래 3가지 요건 모두 충족 시\n\n1) 해외 우수 대학원 박사과정(PhD)의 입학허가 받은 신입생(재학생 지원 불가)\n\n2) 대한민국 국적 보유자 (국외 영주권자 또는 "
          department_id: 65
          department_name: 컴퓨터공학부
          tags:
            - 학사 (대학원)
            - 장학
      title: ''
