openapi: 3.0.0
info:
  title: user
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users/me/:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get user me:
                  value:
                    id: 1
                    username: eldpswp99
                    email: asdf@naver.com
                    keywords:
                      - 장학
                      - 인턴
        '401':
          description: |-
            Unauthorized
            access_token 신규 혹은 재발급 필요
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
              examples:
                invalid token:
                  value:
                    statusCode: 401
                    message: Unauthorized
      operationId: get-user-me
      description: Retrieve the information of the user him/herself.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [access_token]'
    patch:
      summary: Update User Information
      operationId: patch-user-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                update user me:
                  value:
                    id: 1
                    username: eldpswp99
                    email: Rebecca@email.com
                    keywords:
                      - 장학
                      - 인턴
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                Bad request:
                  value:
                    statusCode: 400
                    message: Duplicate Username Error
                    error: Bad Request
        '401':
          description: |-
            Unauthorized
            access_token 신규 혹은 재발급 필요
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
              examples:
                Invalid token:
                  value:
                    statusCode: 401
                    message: Unauthorized
      description: Update the infromation of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            examples:
              Update nickname:
                value:
                  email: Rebecca@email.com
        description: Patch user properties to update.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
    delete:
      summary: ''
      operationId: delete-users-me
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                삭제:
                  value:
                    username: username1
                    nickname: nickname111
                    keywords:
                      - asdf
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                x-examples:
                  example-1:
                    statusCode: 401
                    message: Unauthorized
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      description: 유저 삭제
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
  /users/:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '201':
          description: |-
            User Created,

            access_token을 통해 authentication을 진행하며, 만료 후에는 /user/auth/를 통해 access_token을 새로 발급받아야합니다. access token을 새로 발급받을 때에 refresh_token 또한 새로 발급됩니다.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenUser'
              examples:
                post user example:
                  value:
                    id: 21
                    username: mmmas
                    email: mmmas@email.com
                    access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1tbWFzIiwiaWQiOjIxLCJpYXQiOjE2MTMyNzk1NjgsImV4cCI6MTYxMzI4MzE2OH0.f-3buI9Hku6j15r7MRFmTFrkopYEgeBBvkGxXMweMGw
                    refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1tbWFzIiwiaWQiOjIxLCJpYXQiOjE2MTMyNzk1Njh9.Sl-785nKn45ZKAZyX1r2IYrqc8OnctuOSCTaWryIeEc
                    keywords: []
            application/xml:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties: {}
            text/html:
              schema:
                type: object
                properties: {}
            text/plain:
              schema:
                type: object
                properties: {}
            application/EDI-X12:
              schema:
                type: object
                properties: {}
            json:
              schema:
                type: object
                properties: {}
          headers: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                아이디 중복 시:
                  value:
                    statusCode: 400
                    message: 이미 동일한 아이디가 사용중입니다.
                    error: Bad Request
                닉네임 중복 시:
                  value:
                    statusCode: 400
                    message: 이미 동일한 닉네임이 사용중입니다.
                    error: Bad Request
            application/xml:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
              required:
                - username
                - password
                - email
            examples:
              post user example:
                value:
                  username: eldpswp99
                  password: password
                  email: email@naver.com
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    parameters: []
  /users/auth/token/:
    parameters: []
    post:
      summary: User Authentication
      operationId: post-user-auth
      responses:
        '200':
          description: 'access_token을 통해 authentication을 진행하며, 만료 후에는 /user/auth/token/를 통해 access_token을 새로 발급받아야합니다. access token을 새로 발급받을 때에 refresh_token 또한 새로 발급됩니다.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenUser'
              examples:
                example-1:
                  value:
                    id: 1
                    username: eldpswp99
                    email: email@naver.com
                    access_token: access_token
                    refresh_token: refresh_token
                    keywords: []
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                example-1:
                  value:
                    statusCode: 400
                    message: 'grant_type must be one of the following values: password, refresh_token'
                    error: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    statusCode: 401
                    message: 아이디 혹은 비밀번호가 잘못되었습니다.
                    error: Unauthorized
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
              examples:
                refresh token 인증 실패 시:
                  value:
                    statusCode: 401
                    message: Unauthorized
                'id/password 인증 실패 시 ':
                  value:
                    statusCode: 401
                    message: 아이디 혹은 비밀번호가 잘못되었습니다.
                    error: Unauthorized
      description: user authentication
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                grant_type:
                  type: string
                  minLength: 1
                username:
                  type: string
                  minLength: 1
                password:
                  type: string
                  minLength: 1
              required:
                - grant_type
            examples:
              password authentication:
                value:
                  grant_type: password
                  username: eldpswp99
                  password: password
              refresh_token authentication:
                value:
                  grant_type: refresh_token
        description: |-
          refresh_token 인증 방법을 이용할 시 

          header에 refresh_token이 Authorization으로 제공되어야 합니다.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [refresh_token]'
  /users/me/keyword:
    post:
      summary: Create user keyword
      operationId: post-users-me-keyword
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 1
                    username: eldpswp99
                    email: asdf@naver.com
                    keywords:
                      - 장학
                      - 인턴
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                example-1:
                  value:
                    statusCode: 400
                    message: keyword already added to this user
                    error: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
            examples:
              example-1:
                value:
                  keyword: 장학
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
      description: keyword를 새로 등록합니다.
    delete:
      summary: Delete User keyword
      operationId: delete-users-me-keyword
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 1
                    username: eldpswp99
                    nickname: nickname
                    keywords:
                      - 장학
                      - 인턴
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
              examples:
                example-1:
                  value:
                    statusCode: 401
                    message: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
            examples:
              example-1:
                value:
                  keyword: 장학
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer [token]'
      description: '등록된 keyword를 삭제합니다.없는 키워드를 지우려고 하는 경우 204를 리턴하지만, 유저에 대한 정보는 주지 않습니다.'
components:
  schemas:
    User:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 1
          username: eldpswp99
          nickname: nickname
          keywords:
            - 장학
            - 인턴
      properties:
        id:
          type: number
        username:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        keywords:
          type: array
          items:
            type: string
      required:
        - id
        - username
        - email
        - keywords
    tokenUser:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 1
          username: eldpswp99
          nickname: nickname
          access_token: access_token
          refresh_token: refresh_token
          expires_at: '2020-03-16T17:40:00+09:00'
          keywords:
            - 장학
      properties:
        id:
          type: number
        username:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        access_token:
          type: string
          minLength: 1
        refresh_token:
          type: string
          minLength: 1
        keywords:
          type: array
          items:
            type: string
      required:
        - id
        - username
        - email
        - access_token
        - refresh_token
        - keywords
    Unauthorized:
      description: ''
      type: object
      properties:
        statusCode:
          type: number
        message:
          type: string
          minLength: 1
      required:
        - statusCode
        - message
      x-examples:
        example-1:
          statusCode: 401
          message: Unauthorized
